name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/custom-http-server:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/custom-http-server:${{ github.sha }} \
                     ${{ secrets.DOCKER_USERNAME }}/custom-http-server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/custom-http-server:latest
  smoke-test:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/custom-http-server:latest

      - name: Start container
        run: |
          docker run -d --name smoke \
            -e API_KEY=${{ secrets.API_KEY }} \
            -p 3000:3000 \
            ${{ secrets.DOCKER_USERNAME }}/custom-http-server:latest

      - name: Wait for /health to be healthy
        run: |
          for i in {1..10}; do
            if curl -sf -H "x-api-key:${{ secrets.API_KEY }}" http://localhost:3000/health; then
              echo "healthy"; exit 0
            fi
            echo "waiting…"; sleep 2
          done
          echo "never became healthy"; exit 1

      - name: Smoke-test /compute
        run: |
          curl -sf -H "x-api-key:${{ secrets.API_KEY }}" http://localhost:3000/compute \
            && echo "/compute OK" \
            || (echo " /compute failed"; exit 1)

      - name: Tear down container
        if: always()
        run: docker stop smoke